"""empty message

Revision ID: 580705ed21f7
Revises: a755d610077d
Create Date: 2024-02-05 15:48:54.451502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580705ed21f7'
down_revision = 'a755d610077d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_produit', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('prix', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produit')
    # ### end Alembic commands ###
