"""empty message

Revision ID: bce121e0e002
Revises: 580705ed21f7
Create Date: 2024-02-06 08:35:17.967554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce121e0e002'
down_revision = '580705ed21f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('details', sa.String(length=100), nullable=True))
        batch_op.drop_column('nom_produit')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('nom_produit', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('details')
        batch_op.drop_column('image')
        batch_op.drop_column('name')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
